### PR TITLE
Adding prepublish script

### LINKED ISSUE #10: Build before publish
We just need to put prepublish task on package

### PR DESCRIPTION
**Pull request by caueops**
Fixes #10 

My idea is to running the tests and build before publish a new version of package.

What do you think?

### CODE REVIEW

**Comment by willianjusten** [comment]
Our main problem is when we forget to commit the build before tag/publish. I did the same as yours, but won't fix this issue...=/

What we have to do is:

build => 
verify if we have differences between builds =>
commit =>
tag =>
publish.

I don't know if I'm clear about it....

**Comment by willianjusten** [comment]
@Nipher

**Comment by jmpas** [comment]
I'm not sure which step would be better to add the build procedure...

Actually I was thinking about creating a precommit that:
- Runs tests / lints
- Builds
- Runs `git add dist` (we can do a very simple js file to execute it)

And then we wouldn´t need to include these steps on prepush/prepublish anymore as we just push/publish what is commited, am I right?

And imho this is a MUST before commiting...

What do you guys think?

**Comment by jmpas** [comment]
And you mentioned a tag step for prepublish right?
do you want to automate this? @willianjusten 
because if so, it would be nice to sync between tag and `package.json` version...

Then in my head, it would become something like this:
- get semver version from user (?)
- Updates package.json
- git add and git commit ( with a default message for new version release ?)
- git tag
- publish

**Comment by willianjusten** [comment]
If we put tests/lint before every commit, will be very very annoying...

**Comment by willianjusten** [comment]
I don't want to create something very complicated to users also...=/

**Comment by willianjusten** [comment]
Guys guys!! I was reading a little bit more about npm cli and...they do exactly what we need!

[npm version command](https://docs.npmjs.com/cli/version)

They change the package.json, commit and create a tag.

**Comment by jmpas** [comment]
Omg... I'm so fu#%$ng dumb... :joy: 

Awesome then... could you define what will be done with prepublish?

`build` -> `npm version command` -> `publish` ??

**Comment by willianjusten** [comment]
I'll test if they just add the package.json in the commit or whole modifications. Let me check this.

**Comment by willianjusten** [comment]
Meh...if the working directory has files to be committed yet, the command break =/

**Comment by caueops** [comment]
Hey guys, sorry for delay.

Hmm, I understand the problem. 

It's possible to use the `npm version command` within another script and and call it on `prepublish`.

In this way, the script can commit the files.

**Comment by caueops** [comment]
@willianjusten and @Nipher I will be close the `P.R` for discuss the implementation at #10

**Pull request closed without merging**
